### ISSUE TITLE
nanosecond support 

### ISSUE THREAD

**Issue by nokute78** [fluent/fluent-bit#193]
Fluentd supports nanosecond resolution.
Fluent-bit supports nanosecond interval, but the timestamp of record is in second.
e.g. in_forward of fluent-bit can't handle records from fluentd.

## Roadmap

I suggests these 4 steps to fix from output to input.
It affects so wide, it is better to fix v0.12 or later.

1. define flb_time struct and utilities. (append to msgpack, pop from msgpack, generate flb_time ...)
2. modify output plugins.
3. modify filter plugins.
4. modify input plugins.

## Spec of fluentd 

There are 4 types.

* Unixtime (fluent-bit already supports)
* 3 types of Eventtime 

```
+----+----+----+----+----+----+----+----+----+----+
|  1 |  2 |  3 |  4 |  5 |  6 |  7 |  8 |  9 | 10 |
+----+----+----+----+----+----+----+----+----+----+
| C7 | 00 | second from epoch |     nanosecond    |
+----+----+----+----+----+----+----+----+----+----+
|ext |type| 32bits integer BE | 32bits integer BE |
+----+----+----+----+----+----+----+----+----+----+

+-------+----+----+----+----+----+----+----+----+----+
|     1 |  2 |  3 |  4 |  5 |  6 |  7 |  8 |  9 | 10 |
+-------+----+----+----+----+----+----+----+----+----+
|    D7 | 00 | second from epoch |     nanosecond    |
+-------+----+----+----+----+----+----+----+----+----+
|fixext8|type| 32bits integer BE | 32bits integer BE |
+-------+----+----+----+----+----+----+----+----+----+

+--------+----+----+----+----+----+----+----+----+----+----+
|      1 |  2 |  3 |  4 |  5 |  6 |  7 |  8 |  9 | 10 | 11 |
+--------+----+----+----+----+----+----+----+----+----+----+
|     C7 | 08 | 00 | second from epoch |     nanosecond    |
+--------+----+----+----+----+----+----+----+----+----+----+
|   ext8 | len|type| 32bits integer BE | 32bits integer BE |
+--------+----+----+----+----+----+----+----+----+----+----+
```

See also fluentd wiki
https://github.com/fluent/fluentd/wiki/Forward-Protocol-Specification-v0#entry
https://github.com/fluent/fluentd/wiki/Forward-Protocol-Specification-v0#eventtime-ext-format

https://github.com/fluent/fluentd/wiki/Forward-Protocol-Specification-v1#entry
https://github.com/fluent/fluentd/wiki/Forward-Protocol-Specification-v1#eventtime-ext-format

**Comment by nokute78** [comment]
We can choice 3 functions.
`timespec_get` or `clock_gettime` seem to be proper.

## timespec_get

C11 suports that function.This means Windows also supports.
However, some environments don't support it because this function is defined recently.
http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1570.pdf　  -7.27.2.5 The timespec_get function
https://msdn.microsoft.com/en-us/library/mt633792.aspx

We can get `struct timespec` with this function.
```
struct timespec {
    time_t   tv_sec;        /* seconds */
    long     tv_nsec;       /* nanoseconds */
};
```

## clock_gettime

We can also get timespec with this function.
POSIX supports it.
It may be better to use this function on a environment which doesn't support timespec_get.

## gettimeofday

This function returns timeval which is in microsecond and the function will be obsoleted via POSIX.1-2008.

**Comment by edsiper** [comment]
note: @nokute78 have implemented Nanosecond support, here is a list of plugins that needs to be adapted/checked:

- [ ] in_cpu
- [ ] in_disk
- [ ] in_format
- [ ] in_head
- [ ] in_health
- [ ] in_kmsg
- [ ] in_lib
- [ ] in_mem
- [ ] in_mqtt
- [ ] in_proc
- [ ] in_random
- [ ] in_serial
- [ ] in_stdin
- [ ] in_syslog
- [ ] in_tail
- [ ] in_tcp
- [x] out_counter
- [ ] out_es
- [ ] out_file
- [ ] out_flowcounter
- [ ] out_forward
- [ ] out_http
- [ ] out_influxdb
- [ ] out_lib
- [ ] out_nats
- [ ] out_plot
- [x] out_stdout
- [ ] out_td

**Comment by edsiper** [comment]
Most of plugins already migrated, pending ones are in_lib & out_lib.

**Comment by nokute78** [comment]
@edsiper Thank you so much!

Could you add 
- [x] filter_grep (no changes required)
- [x] filter_kubernetes (no changes required)
- [x] out_null(no changes required)

to list to record that we considered them and decided nothing to do.

And could you review #236 and #237 ?

**Comment by edsiper** [comment]
done.

**Comment by nokute78** [comment]
Thanks!

**Comment by edsiper** [comment]
So Nanoseconds support is complete! thanks @nokute78 !

**Comment by edsiper** [comment]
Since all components now supports nanoseconds, I am closing this issue. Any problem created by these changed should be addressed in new tickets.
