### ISSUE TITLE
1.9: Track release and pendings

### ISSUE THREAD

**Issue by edsiper** [fluent/fluent-bit#4581]
Tracking missing  changes or PRs reviews for 1.9 (edition in progress)

- Core
  - [x] New config reader with YAML support (#4621)
  - [x] Ability to run input plugins in a separate thread (WIP #4586)
  - [ ] Expose storage metrics in fluentbit_metrics input plugin
  - [x] I/O Sync timeouts (#4184)
  - [ ] Integrate Chunk I/O 1.2.0 (new cached stats feature)
  - Network / OpenSSL
    - [x] https://github.com/fluent/fluent-bit/pull/4100
    - [ ] https://github.com/fluent/fluent-bit/pull/4290
- Plugins
  - [x] Nginx Plus metrics (#4379)
  - [ ] Logs to metrics filter
  - [x] Experimental Windows Metrics Collector (#4391 )
  - [x] Kafka Input (WIP, requires #4586)
  - [x] OpenSearch Output (experimental version) (#4807)
  - [x] BigQuery: support AWS auth via GCP Workload Identity Federation (#4282)
  - [x] Apache SkyWalking (#3592)
  - [x] https://github.com/fluent/fluent-bit/pull/4496

**Comment by leonardo-albertovich** [comment]
I think for the Windows Metrics Collector the correct PR is #4391 because #4398 was a backport which we won't do since this is scheduled to be released in 1.9, also, I removed the "Do not merge" footnote since the plugin was reviewed by Hiroshi.

**Comment by edsiper** [comment]
@leonardo-albertovich thanks, fixed.

**Comment by agup006** [comment]
@edsiper can we add this to plugin list as well? https://github.com/fluent/fluent-bit/pull/3592

**Comment by edsiper** [comment]
> @edsiper can we add this to plugin list as well? #3592

done

**Comment by tarruda** [comment]
in_kafka POC PR: https://github.com/fluent/fluent-bit/pull/4641

**Comment by leonardo-albertovich** [comment]
We need to port #4501 to master

**Comment by leonardo-albertovich** [comment]
We wanted to ensure this is changed in 1.9 : #3581 which was caused by fluent-bit not being built with openssl in some platforms.
