### ISSUE TITLE
1.8.12: Track release and pendings -WIP-

### ISSUE THREAD

**Issue by lecaros** [fluent/fluent-bit#4645]
Core:
- [x] :heavy_check_mark: https://github.com/fluent/fluent-bit/pull/4590 (master & 1.8)
- [x] :heavy_check_mark: https://github.com/fluent/fluent-bit/pull/4355 related to #4300 (merged for 1.8.11)
- [x] :heavy_check_mark: https://github.com/fluent/fluent-bit/pull/4362 related to #4300 (merged for 1.8.11)
- [x] :heavy_check_mark:  https://github.com/fluent/fluent-bit/pull/4140 related to #4300, merged to master already. Merged #4645 for 1.8
- [x] :heavy_check_mark: :  https://github.com/fluent/fluent-bit/pull/4605. Merged to master. Waiting for PR #4659 for 1.8
- [x] :heavy_check_mark: https://github.com/fluent/fluent-bit/pull/4420 related to #4300 (merged in master and 1.8)
- [x] :heavy_check_mark: https://github.com/fluent/fluent-bit/pull/4474 related to #4300.
- [x] :heavy_check_mark: https://github.com/fluent/fluent-bit/pull/4501 (merged)

Plugins:
- [x] :heavy_check_mark:  https://github.com/fluent/fluent-bit/pull/4655 (merged in 1.8)
- [x] :heavy_check_mark: :  https://github.com/fluent/fluent-bit/pull/4422  Upgrade mbedtls to 2.28. Includes Core and S3 plugin. Merged in 1.8 #4661
- [x] https://github.com/fluent/fluent-bit/pull/4466 Already merged to 1.8. Need docs
- [x] :heavy_check_mark:   https://github.com/fluent/fluent-bit/pull/4663 
- [x] :heavy_check_mark:   https://github.com/fluent/fluent-bit/pull/4668
- [x] :heavy_check_mark: #4675
- [x] :heavy_check_mark: https://github.com/fluent/fluent-bit/pull/4678

**Comment by nokute78** [comment]
Could you add https://github.com/fluent/fluent-bit/pull/4517 ?
It has not been merged 1.8 branch yet and user requested https://github.com/fluent/fluent-bit/pull/4517#issuecomment-1018559617.

**Comment by edsiper** [comment]
@nokute78 done, waiting for CI

**Comment by nokute78** [comment]
@edsiper Thank you.

**Comment by nokute78** [comment]
By the way, how about using milestone to track issue/PR ?
There is already https://github.com/fluent/fluent-bit/milestone/12 for v1.8.12.

**Comment by edsiper** [comment]
good idea, @lecaros ^

**Comment by nokute78** [comment]
We can add issue/PR to milestone below menu or 
https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/associating-milestones-with-issues-and-pull-requests


<img width="882" alt="milestone" src="https://user-images.githubusercontent.com/16795275/150659341-c891b8c2-1853-4d6c-823f-dd6e8fd07369.png">

**Comment by jerome-leanspace** [comment]
I'm writing here because it seems related but I can create a new issue if needed
I can already see the 1.8.12 version in docker and the 1.8 and (-debug) was updated and they seem to be quite different, 1.8-debug is much bigger and doesn't have busybox or was moved to another location

**Comment by patrick-stephens** [comment]
1.8.12 moves to Debian 11 (Bullseye).
Busybox has been removed as the debug images are just `bullseye-slim` ones so already have a shell (in fact sh and bash) and package manager. Is there a specific issue without it as we probably do need to resolve that so please raise and tag me?

**Comment by patrick-stephens** [comment]
@jerome-leanspace just to check - are you all ok with the removal of Busybox? I want to make sure I've not missed something or we need to add any other tooling back in.

**Comment by jerome-leanspace** [comment]
@patrick-stephens yes I'm fine with it, however the change is not documented in the release notes or on the website (https://docs.fluentbit.io/manual/installation/docker)

**Comment by patrick-stephens** [comment]
Yes, I thought I had raised a PR on docs but will fix that now.
The change notes should capture it in 1.9+ as the dockerfiles are all in the main repo now but for 1.8.12 this was a last minute backport via the deprecated repo so got missed.

**Comment by agup006** [comment]
With 1.8.12 shipped I believe we can close
